import type { Report } from '../types/report'

const mockReports: Report[] = [
  {
    id: 'REP-401',
    name: 'Main Branch Drift Scan',
    summary: 'Primary scan for current branch with high-confidence stale documentation findings.',
    reportType: 'scan-summary',
    project: 'docrot-detector',
    trigger: 'github-actions',
    scanLabel: 'Scan #2026-02-26-A',
    issueCount: 4,
    status: 'warning',
    createdAt: '2026-02-26T19:39:30.859618',
  },
  {
    id: 'REP-402',
    name: 'Nightly CI Baseline',
    summary: 'Baseline drift status generated by nightly CI job after doc synchronization.',
    reportType: 'ci-run',
    project: 'docrot-detector',
    trigger: 'github-actions',
    scanLabel: 'Scan #2026-02-25-N',
    issueCount: 1,
    status: 'complete',
    createdAt: '2026-02-25T03:10:00.000Z',
  },
  {
    id: 'REP-403',
    name: 'Manual Validation Pass',
    summary: 'Manual scanner execution performed before release docs lock.',
    reportType: 'mismatch-breakdown',
    project: 'docrot-detector',
    trigger: 'manual-cli',
    scanLabel: 'Scan #2026-02-24-M',
    issueCount: 2,
    status: 'warning',
    createdAt: '2026-03-03T12:00:00.000Z',
  },
]

export function useReports() {
  const reports = mockReports

  const loading = false
  const error: string | null = null

  return {
    reports,
    loading,
    error,
  }
}
